# Generated by Django 5.1.5 on 2025-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='profile',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='about_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='avatar',
            field=models.FileField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
